spring:
  datasource:
    name: test  #\u6570\u636E\u5E93\u540D
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root  #\u7528\u6237\u540D
    password: root  #\u5BC6\u7801
    driver-class-name: com.mysql.cj.jdbc.Driver  #\u6570\u636E\u5E93\u94FE\u63A5\u9A71\u52A8


mybatis:
  mapper-locations: classpath:mapper/*.xml  #\u914D\u7F6E\u6620\u5C04\u6587\u4EF6
  type-aliases-package: com.example.bean #\u914D\u7F6E\u5B9E\u4F53\u7C7B